### ISSUE TITLE
Include ISSNs in indexing, review ISBNs

### ISSUE THREAD

**Issue by ruthtillman** [psu-libraries/psulib_traject#101]
While I'd thought ISSNs were in the default index, only ISBNs are. Review both fields and update as appropriate. Wiki page here: https://github.com/psu-libraries/psulib_blacklight/wiki/ISSNs-and-ISBNs

**Comment by cdmo** [comment]
Just so this is clear, Blacklight has built-in methods for parsing/normalizing/transforming ISBN and ISSN (it's in `StdNum::ISBN` and `StdNum::ISSN`)

**Comment by cdmo** [comment]
Not sure why ISSN isn't in the default mapping. Probably an oversight. 🤷‍♂️

**Comment by ruthtillman** [comment]
it's so fundamental I'd just assumed... but maybe it was taken out at one point.

**Comment by cdmo** [comment]
Reading over the wiki, I didn't see this represented, so I just wanted to put it out there, sometimes ISBNs in our catalog have suffixes like:

`69           isbn                 0884559963 (v. 1) : | 9780884559962 (v. 1)`

or `0071882279 (pbk.)` (for record with catkey 199)

or 

`420          isbn                 0802028314 (set) | 0802005365 (v. 11) | 0802048315 (v. 12) | 9780802090591 (v. 13) | 9781442640443 (v. 14) | 9781442642034 (v. 15) | 9781442647497 (v. 16) | 9781442648784 | 1442648783 | 9781487501990 ǂq (v. 18) | 1487501994 ǂq (v. 18) | 0802028314 (v. 34) | 0802036430 (v. 35) | 0802088325 (v. 36) | 9781442641662 (v. 37-38) | 0802058590 (v. 46) | 9780802092960 (v. 43) | 0802005411 (v. 44) | 9780802092991 (v. 45) | 0802036538 (v. 48) | 0802004790 (v. 49) | 0802006647 (v. 50) | 0802028039 (v. 56) | 0802027601 (v. 61) | 0802043089 (v. 63) | 0802035841 (v. 64) | 9780802099792 (v. 65) | 0802026567 (v. 66) | 0802038360 (v. 72) | 9781442648944 (v. 73) | 0802043178 (v. 76) | 0802047564 (v. 77) | 9780802098665 (v. 78) | 9781442641150 (v. 82) | 0802043100 (v. 83) | 0802043976 (v. 84) | 0802028675 (v. 85-86)`

Blacklight normalizes these parenthetical suffixes out instead of attempting to reconcile them. I assume that the parenthetical suffix has local meaning in our catalog when there are multiple holdings in a record. Thought with this 420 one there is no version 1-10... Guessing it's okay to ignore these, at least for now?

**Comment by cdmo** [comment]
Some of our `020a`s have some parenthetical suffixes, like [420](blackcat01qa.libraries.psu.edu/catalog/420). I assume they have local meaning when there are multiple separate holdings as a way to add a relationship. Either way, we are stripping them via the core logic of Blacklight's ISBN normalization at the moment. Just noticed this so I thought I'd add it since I didn't see it on the wiki page.

**Comment by cdmo** [comment]
Thanks (and sorry I deleted my comment and re-stated it for clarity)

For 420 we'll index 

```
9780802028310 | 0802028314 | 9780802005366 | 0802005365 | 9780802048318 | 0802048315 | 9780802090591 | 0802090591 | 9781442640443 | 1442640448 | 9781442642034 | 1442642033 | 9781442647497 | 1442647493 | 9781442648784 | 1442648783 | 9781487501990 | 1487501994 | 9780802036438 | 0802036430 | 9780802088321 | 0802088325 | 9781442641662 | 1442641665 | 9780802058591 | 0802058590 | 9780802092960 | 0802092969 | 9780802005410 | 0802005411 | 9780802092991 | 0802092993 | 9780802036537 | 0802036538 | 0802004790 | 9780802006646 | 0802006647 | 9780802028037 | 0802028039 | 9780802027603 | 0802027601 | 9780802043085 | 0802043089 | 9780802035844 | 0802035841 | 9780802099792 | 0802099793 | 9780802026569 | 0802026567 | 9780802038364 | 0802038360 | 9781442648944 | 1442648945 | 9780802043177 | 0802043178 | 9780802047564 | 0802047564 | 9780802098665 | 0802098665 | 9781442641150 | 1442641150 | 9780802043108 | 0802043100 | 9780802043979 | 0802043976 | 9780802028679 | 0802028675
```

And dispaly

```
0802028314 (set) | 0802005365 (v. 11) | 0802048315 (v. 12) | 9780802090591 (v. 13) | 9781442640443 (v. 14) | 9781442642034 (v. 15) | 9781442647497 (v. 16) | 9781442648784 | (v. 17) | 1442648783 | 9781487501990 ǂq (v. 18) | 1487501994 ǂq (v. 18) | 0802028314 (v. 34) | 0802036430 (v. 35) | 0802088325 (v. 36) | 9781442641662 (v. 37-38) | 0802058590 (v. 46) | 9780802092960 (v. 43) | 0802005411 (v. 44) | 9780802092991 (v. 45) | 0802036538 (v. 48) | 0802004790 (v. 49) | 0802006647 (v. 50) | 0802028039 (v. 56) | 0802027601 (v. 61) | 0802043089 (v. 63) | 0802035841 (v. 64) | 9780802099792 (v. 65) | 0802026567 (v. 66) | 0802038360 (v. 72) | 9781442648944 (v. 73) | 0802043178 (v. 76) | 0802047564 (v. 77) | 9780802098665 (v. 78) | 9781442641150 (v. 82) | 0802043100 (v. 83) | 0802043976 (v. 84) | 0802028675 (v. 85-86)
```

**Comment by cdmo** [comment]
![screenshot 2019-03-05 11 58 44](https://user-images.githubusercontent.com/523381/53822601-0ff8da00-3f3e-11e9-8cac-015a3d790336.png)

This record, 5826 looks like `020   a| 0854099662 : c| £2.00`

And I think the intention of the colon is display. Should we keep the colon? This is just one example, there are lots of them in the CAT. Also, I'm guessing the intention is to have the price (`c`) be inline.

**Comment by ruthtillman** [comment]
no, let's strip spaces/colons. 

And re: c, actually maybe let's strip those out? ... it just seems weird to include prices. (and/or can we see whether we get variations of the c other than $?)

**Comment by cdmo** [comment]
yeah I was wondering about that subfield. Here's some a bunch more subfield `c`s:

```
69           isbn_ssm                  $25.00
845          isbn_ssm                  £6.00
993          isbn_ssm                  £6.50 ($17.00 U.S.)
1046         isbn_ssm                  $3.95
2119         isbn_ssm                  £7.20
2285         isbn_ssm                  $19.50 (U.S.)
2571         isbn_ssm                  $2.95
3594         isbn_ssm                  $6.50
3997         isbn_ssm                  £L35.00
4091         isbn_ssm                  £18.00
4605         isbn_ssm                  £8.50
5086         isbn_ssm                  Y3000 ($15.00 U.S.)
5325         isbn_ssm                  £12.50
5358         isbn_ssm                  £0.75 ($1.20 U.S.)
5425         isbn_ssm                  £5.25
5490         isbn_ssm                  £4.50
5782         isbn_ssm                  £2.75
5826         isbn_ssm                  £2.00
5872         isbn_ssm                  £3.50
5998         isbn_ssm                  £5.30
5999         isbn_ssm                  £8.50
6761         isbn_ssm                  £16.00 (v. 1-2)
7213         isbn_ssm                  98.00F
7460         isbn_ssm                  £8.50 ($27.25 U.S.)
7572         isbn_ssm                  £4.25
7689         isbn_ssm                  $10.75
7778         isbn_ssm                  $6.95
9377         isbn_ssm                  $16.75 (U.S.)
9434         isbn_ssm                  pbk.
9482         isbn_ssm                  £7.50
9729         isbn_ssm                  £7.00
9815         isbn_ssm                  £13.00
9832         isbn_ssm                  £3.00
9861         isbn_ssm                  £10.00
9904         isbn_ssm                  £12.50
9960         isbn_ssm                  DM24.50
10145        isbn_ssm                  $7.50.
10170        isbn_ssm                  NT$180.00 ($5.20 U.S.)
10184        isbn_ssm                  $4.95
10196        isbn_ssm                  NT$600.00
10301        isbn_ssm                  $21.50
10436        isbn_ssm                  fl 55.00
10476        isbn_ssm                  Y400
10515        isbn_ssm                  Y980
10945        isbn_ssm                  £4.75
11252        isbn_ssm                  $13.50
11278        isbn_ssm                  $9.95
11318        isbn_ssm                  $16.00
11323        isbn_ssm                  $6.95
11390        isbn_ssm                  $7.95
11426        isbn_ssm                  £8.50
11947        isbn_ssm                  R12.50
12109        isbn_ssm                  £6.00.
```

**Comment by ruthtillman** [comment]
thanks @cdmo ok let's not do c. I'll update the wiki.

**Comment by ruthtillman** [comment]
This all looks good!

**Comment by banukutlu** [comment]
@ruthtillman Could you pls check ISBN's of this record: https://blackcat01qa.libraries.psu.edu/catalog/21601671

```
020      a| 9780822368939 q| hardcover ; q| alkaline paper
020      a| 0822368935 q| hardcover ; q| alkaline paper
020      a| 9780822369196 q| paperback ; q| alkaline paper
020      a| 0822369192 q| paperback ; q| alkaline paper
```

Seems like we need to decide whether to display subfield q or not and if so how to display? 

@cdmo

**Comment by ruthtillman** [comment]
Ah good catch! So what we'd need to do for the display is index the 020aqq (I think that's how to be sure we catch multiples but maybe one should be sure?) leaving out any c and display each 020 field on its own line.

020 will repeat but you will only have one 020a per 020 (it's specifically non-repeatable)

**Comment by ruthtillman** [comment]
Do we have a plan to resolve the issue of displaying format qualifiers in line with ISBNs? https://blackcat01qa.libraries.psu.edu/catalog/22599844
