### ISSUE TITLE
Indexing concurrency problem

### ISSUE THREAD

**Issue by banukutlu** [psu-libraries/psulib_traject#132]
regexes + capture groups are broken by design when used in lambdas: `https://github.com/jruby/jruby/issues/4868` 

Stanford's workaround: https://github.com/sul-dlss/searchworks_traject_indexer/blob/master/lib/traject/config/sirsi_config.rb#L1982-L1990

**Comment by cdmo** [comment]
We fixed this with a BIG help from Chris Beer from SUL. The problem is that jruby acts differently then MRI in regards to regex.

See https://github.com/jruby/jruby/issues/4868 and solution in https://github.com/sul-dlss/searchworks_traject_indexer/blob/master/lib/traject/config/sirsi_config.rb#L1982-L1990

Patch to close this coming soon
