### ISSUE TITLE
Remove date 9999 from consideration

### ISSUE THREAD

**Issue by ruthtillman** [psu-libraries/psulib_traject#163]
The date 9999 is supposed to be used when things are open-ended. It's sometimes also used because of poor data choices.

We do not want it to carry any weight in:

1. date ranges (e.g. facet)
2. relevancy ranking

Example records?

**Comment by ruthtillman** [comment]
https://www.oclc.org/bibformats/en/fixedfield/dates.html

**Comment by ruthtillman** [comment]
Things we discussed:

1. If date is _only_ 9999, then make it have no date? Or does this break the system?
2. If having no date breaks the system, then should we substitute some kind of range like 1990-2010 generically?

**Comment by nicktiberi** [comment]
Currently, traject attempts to ignore publication dates below 500 and above `current_year + 6`, but the code that tries to determine that is broken and it's doing the check incorrectly, so that's why records with date `9999` are slipping through the cracks. Do we want to retain this logic, @ruthtillman, or should we modify the min/max dates in some way?
