### ISSUE TITLE
Review full and partial links rules

### ISSUE THREAD

**Issue by banukutlu** [psu-libraries/psulib_traject#301]
Full links available? rule:
`(ind2 == '0' || ind1 == '4' || (ind1.strip.empty? && ind2.strip.empty?)) && !NOT_FULLTEXT.match?(url_label)`

Partial links available? rule:
`ind2 == '1' || ((ind2 == '0' || ind1 == '4') && NOT_FULLTEXT.match?(url_label))`

856s like the below are both full and partial:
`856 4 1 3| v.19-20 Sept.1939-May 1941 u| http://archive.org/details/facultybulletinp00penn`

**Comment by ruthtillman** [comment]
So what it looks like there are several different kinds of collisions which can happen, including Partial and Suppl rules which are colliding e.g. https://catalog.libraries.psu.edu/catalog/2171372/raw.json (but this raises an issue with our link labeling which I put in the other issue).

Looking at this:

```
    def fulltext_link_available?(ind1, ind2, url_label)
      (ind2 == '0' || ind1 == '4' || (ind1.strip.empty? && ind2.strip.empty?)) && !NOT_FULLTEXT.match?(url_label)
    end

    def partial_link_available?(ind1, ind2, url_label)
      ind2 == '1' || ((ind2 == '0' || ind1 == '4') && NOT_FULLTEXT.match?(url_label))
    end

    def suppl_link_available?(ind2)
      ind2 == '2'
    end
```

In reviewing documentation and options, I am thinking that this might work... Removed the first indicator 4 because while only first indicator 4 are like... good links? ... if we get an FTP link or whatever ? oh well. It might work? Or we get an issue report and remove it from the record.

```ruby

# changing to be (either ind2 is 0 or both inds are blank in which case we have no idea so might as well try fulltext) AND they're NOT NOT_FULLTEXT

   def fulltext_link_available?(ind1, ind2, url_label)
      (ind2 == '0' || (ind1.strip.empty? && ind2.strip.empty?)) && !NOT_FULLTEXT.match?(url_label)
    end

# only small change to remove the ind1 == 4. Partial links either have ind2 == 1 or they're coded like regular links but match the NOT_FULLTEXT criteria.

    def partial_link_available?(ind1, ind2, url_label)
      ind2 == '1' || (ind2 == '0' && NOT_FULLTEXT.match?(url_label))
    end

# leave as is because now we should only be getting related resources here.

    def suppl_link_available?(ind2)
      ind2 == '2'
    end
```

**Comment by ruthtillman** [comment]
Updated Wiki to reflect proposed logic above and can continue to update.
