### ISSUE TITLE
Records without itemids

### ISSUE THREAD

**Issue by banukutlu** [psu-libraries/psulib_traject#43]
In GitLab by @mxk128 on Sep 28, 2018, 15:32

During extraction I saw there were bib records that have a call record but no item record. Some reasons are
*  Bound-with records  #42 
*  cataloging problem

I will add more as I see them

**Comment by banukutlu** [comment]
In GitLab by @mxk128 on Sep 28, 2018, 15:33

changed the description

**Comment by mkutch** [comment]
Note - there is an option in to dump 
  
   ```
-H functions the same as -h, but outputs call number information when no items 
      exist for a call number.
```

**Comment by mkutch** [comment]
We are not extracting bib records that have a call record but no item record AND are not boundwith. For example catkeys `10329251` `1686033` `1185362` `2218122`. 
That means that Special collections records like  i.e. `17280249` `1553014` `7399608 `are not extracted also.
Do we want to have them fix the bib records?

**Comment by ruthtillman** [comment]
I've taken a look at these in both Workflows and The Cat and will be meeting with Annie later today. I hope she'll provide some guidance on next steps. Possibilities may include turning these over to collections maintenance as a report/printout so that they can try tracking them down and add items for ones that exist, or accepting that we just won't include them. I'll update when we get to it.

(with the non-special collections ones, the record is completely un-actionable -- no "I want it" etc., which makes me think it's not worth including. For special collections, it's more complex.)

**Comment by mkutch** [comment]
@ruthtillman I uploaded on box 2 files 

bibrecs_withno_items_not_speccol.txt
bibrecs_withno_items_speccol.txt

The fields of the pipe-delimited files are
```
catkey | title  | call number | call library
```
