### ISSUE TITLE
Records exceeding maximum export size

### ISSUE THREAD

**Issue by banukutlu** [psu-libraries/psulib_traject#47]
Did a full extract and came back with 7 errors our of 7+ million records.

Errors were

```
**holding_tags table exceeded MAXITEMS

**Record exceeds maximum export size
```

I put in a ticket with Sirsi asking if is there a way to find out which catkeys resulted in the 7 errors. 
Their response 

>  "We were only able to find two of the errored records. They were the records causing the "holding_tags table exceeded MAXITEMS" errors. They are Title Control numbers s0727-4181 with 12637 items and s0196-1497 with 10239 items.You can find these records and update them individually and just ignore the errors every time you run a catalog dump or split these catalog record into smaller catalog records." 

So we asked them what do they mean by "just ignore". Does this mean they are included in the dump?

**Comment by mkutch** [comment]
I found one the records that was giving the error

`**Record exceeds maximum export size
`

catkey 244318

The issue seems to be the multiple very long Contents notes field (505) .

**Comment by mkutch** [comment]
I put in a ticket with Sirsi also do get some more info/clarification regarding these 5 records.

**Comment by banukutlu** [comment]
@mkutch can we look into writing a separate dump for these records?

**Comment by mkutch** [comment]
The 2 records that had the "holding_tags table exceeded error

catkey 2168931
catkey 109596

**Comment by mkutch** [comment]
I was going through those 5 large records that had problems exporting and noticed something which I would like if someone (Jeff ?) can clean the records because I am still running into a problem with it. I wrote a script to build the 949s but when I try to convert the file to marc I get

` **Entry too large for data record`

I noticed that the some of the 501 fields are duplicated multiple time.
For instance catkey  6054326 , if you look at the fourth and fifth 501 they are the same except the fourth one has a capital P (Paula) but the fifth 501 has a lowercase p (paula).  In the fourth 501 there is a the word "master," and in the fifth one "master." .
I'm guessing the other 501s in this record have dupes?

I want to ask Jeff to delete the 949 fields in the bib records of these 5 large records if they are not needed?  Per a previous conversation with Jeff , he said 949s can be deleted.
