### ISSUE TITLE
Audience Characteristics indexing, handling subfield m qualifier

### ISSUE THREAD

**Issue by ruthtillman** [psu-libraries/psulib_traject#80]
We're currently indexing the following subfields from audience characteristics, 385:

`385ma3`

Unfortunately, they're essentially stacked qualifiers.

3 - pertains to the work being described
m - free-text label for the kind of audience (age group, language group, educational group, etc.)
a - the actual value

This means that putting any of them together looks weird, e.g.

https://blackcat01qa.libraries.psu.edu/catalog/23171355

```
        Age Children
        Educational level School children
        Educational level Kindergarteners
```

If it were multi-item, it'd be

```
        [Book Title 1] Age Children
        [Book Title 2] Educational level School children
        [Accompanying DVD Title] Educational level Kindergarteners
```

where the bracketed text is standins for actual titles. This would get really complex.

Our options are:

a) only index subfield a and call it a day -- we don't seem to have much or any data at this point with subfield 3 and subfield m can mostly be interpreted by the value in subfield a.

b) index all fields in a way which creates separators. this could be a good back-burner indexing improvement for post-MVP. 385s will continue to accumulate but aren't huge now.

If a, should we start creating an indexing back-burner? We also have the issue of separators in 382, medium of performance.

**Comment by cdmo** [comment]
From my reading of [MARC 21 docs](https://www.loc.gov/marc/bibliographic/bd385.html), it looks like `m` should _always_ be a "designator" for `a`.  So, maybe we throw a colon after `m`'s value when it's present then, because that seems to be the desired human-readable output. Age: Children.

You also said "If it were multi-item, it'd be" -- but I haven't seen any examples of multi-item records with audience descriptions. Do they exist?

Lastly, you said "we don't seem to have much or any data at this point with subfield 3" - and yeah, I haven't seen any. Do they exist?

Should we ask Maryam to help us find if these last two scenarios exist in our catalog?

**Comment by ruthtillman** [comment]
I think it's a pretty unlikely combo. We  could go with `m: a` for now.

**Comment by banukutlu** [comment]
@ruthtillman could you please document this in https://github.com/psu-libraries/psulib_blacklight/wiki/Material-Characteristics-Fields?

**Comment by ruthtillman** [comment]
updated docs.
